const listpacks = [' (vanilla, none, po3normal, po3titan, po3kappa, sf4, ragnamodv, towncraft, amnesia, rusticwaters, astroblock, volcanoblock, stoneblock1, stoneblock2, skyodyssey, chaoticprogression, antichem, madpack4, rad, rlcraft, mceternal, enigmatica4, blissfulbuilding, infinevo, infinevo_expert, skyworkshop, questingmayhem, dimensionzero, ftbacademy, enigmatica2, enigmatica2ex, enigmatica2skyex, enigmatica6, atm3ex, compactclaustrophobia, ftbinteractions)'];

const amnesia = ['The current pack is Amnesia, a modpack that can be found on the Twitch App. >> https://www.curseforge.com/minecraft/modpacks/Amnesia'];
const atm3ex = ['The current pack is All The Mods 3 [Expert], a modpack that can be found on the Twitch App. >> https://www.curseforge.com/minecraft/modpacks/all-the-mods-3-expert'];
const antichem = ['The current pack is AntiMatter Chemistry, a modpack that can be found on the Twitch App. >> https://www.curseforge.com/minecraft/modpacks/antimatter-chemistry'];
const astroblock = ['The current pack is AstroBlock, a modpack that can be found on the Twitch App. >> https://www.curseforge.com/minecraft/modpacks/astroblock'];
const blissfulbuilding = ['The current pack is Blissful Building, a 1.14.4 modpack for the Bliss Stream Team, available on the Twitch App. >> https://www.curseforge.com/minecraft/modpacks/blissful-building'];
const chaoticprogression = ['The current pack is Chaotic Progression, a modpack that can be found on the Twitch App. >> https://www.curseforge.com/minecraft/modpacks/chaotic-progression'];
const compactclaustrophobia = ['The current pack is Compact Claustrophobia, a modpack that can be found on the Twitch App. >> https://www.curseforge.com/minecraft/modpacks/compact-claustrophobia'];
const dimensionzero = ['The current pack is Dimension Zero, a modpack available on the Twitch App. >> https://www.curseforge.com/minecraft/modpacks/dimension-zero'];
const enigmatica2 = ['The current pack is Enigmatica 2, a modpack available on the Twitch App. >> https://www.curseforge.com/minecraft/modpacks/enigmatica2'];
const enigmatica2ex = ['The current pack is Enigmatica 2 [Expert], a modpack available on the Twitch App. >> https://www.curseforge.com/minecraft/modpacks/enigmatica2expert'];
const enigmatica2skyex = ['The current pack is Enigmatica 2: Skyblock [Expert], a modpack available on the Twitch App. >> https://www.curseforge.com/minecraft/modpacks/enigmatica2expertskyblock'];
const enigmatica4 = ['The current pack is Enigmatica 4, a modpack available on the Twitch App. >> https://www.curseforge.com/minecraft/modpacks/enigmatica4'];
const enigmatica6 = ['The current pack is Enigmatica 6, a modpack available on the Twitch App. >> https://www.curseforge.com/minecraft/modpacks/enigmatica6'];
const ftbacademy = ['The current pack is FTB Academy, a modpack available on the Twitch App. >> https://www.curseforge.com/minecraft/modpacks/ftb-academy'];
const ftbinteractions = ['The current pack is FTB Interactions, a modpack available on the FTB App. >> https://www.feed-the-beast.com/modpack/ftb_interactions'];
const infinevo = ['The current pack is FTB Infinity Evolved, a modpack available on the Twitch App. >> https://www.curseforge.com/minecraft/modpacks/ftb-infinity-evolved'];
const infinevo_expert = ['The current pack is FTB Infinity Evolved [Expert], a modpack available on the Twitch App. >> https://www.curseforge.com/minecraft/modpacks/ftb-infinity-evolved'];
const madpack4 = ['The current pack is Madpack 4, a BETA modpack that can be found on the Twitch App. >> https://www.curseforge.com/minecraft/modpacks/madpack-4/'];
const mceternal = ['The current pack is MCEternal, a modpack available on the Twitch App. >> https://www.curseforge.com/minecraft/modpacks/minecraft-eternal'];
const po3normal = ['The current pack is Project Ozone 3 [Normal], a modpack that can be found on the Twitch App. >> https://www.curseforge.com/minecraft/modpacks/project-ozone-3-a-new-way-forward'];
const po3titan = ['The current pack is Project Ozone 3 [Titan], a modpack that can be found on the Twitch App. >> https://www.curseforge.com/minecraft/modpacks/project-ozone-3-a-new-way-forward'];
const po3kappa = ['The current pack is Project Ozone 3 [Kappa], a modpack that can be found on the Twitch App. >> https://www.curseforge.com/minecraft/modpacks/project-ozone-3-a-new-way-forward'];
const questingmayhem = ['The current pack is Questing Mayhem, a modpack available on the Twitch App. >> https://www.curseforge.com/minecraft/modpacks/questing-mayhem'];
const rad = ['The current pack is Roguelike Adventures and Dungeons, a modpack available on the Twitch App. >> https://www.curseforge.com/minecraft/modpacks/roguelike-adventures-and-dungeons'];
const ragnamodv = ['The current pack is Ragnamod V, a modpack that can be found on the Twitch App. >> https://minecraft.curseforge.com/modpacks/ragnamod-v'];
const rlcraft = ['The current pack is RLCraft, a modpack available on the Twitch App. >> https://www.curseforge.com/minecraft/modpacks/rlcraft'];
const rusticwaters = ['The current pack is SeaBlock: Rustic Waters, a modpack that can be found on the Twitch App. >> https://www.curseforge.com/minecraft/modpacks/seablock-rustic-waters'];
const sf4 = ['The current pack is Sky Factory 4, a modpack that can be found on the Twitch App. >> https://minecraft.curseforge.com/projects/skyfactory-4'];
const skyodyssey = ['The current pack is FTB Sky Odyssey, a modpack that can be found on the Twitch App. >> https://www.feed-the-beast.com/projects/ftb-sky-odyssey'];
const skyworkshop = ['The current pack is SkyWorkshop, a modpack available on the Twitch App. >> https://www.curseforge.com/minecraft/modpacks/skyworkshop'];
const stoneblock1 = ['The current pack is StoneBlock 1, a modpack that can be found on the Twitch App. >> https://www.curseforge.com/minecraft/modpacks/stoneblock'];
const stoneblock2 = ['The current pack is StoneBlock 2, a modpack that can be found on the Twitch App. >> https://www.curseforge.com/minecraft/modpacks/ftb-presents-stoneblock-2/'];
const towncraft = ['The current pack is TownCraft, a modpack that can be found on the Twitch App. >> https://minecraft.curseforge.com/projects/towncraft'];
const trillionaire = ['The current pack is Minecraft Trillionaire, a modpack that can be found on the Twitch App. >> https://www.curseforge.com/minecraft/modpacks/minecraft-trillionaire'];
const volcanoblock = ['The current pack is Volcano Block, a modpack that can be found on the Twitch App. >> https://www.curseforge.com/minecraft/modpacks/volcano-block'];

const vanilla = ['This is Vanilla Minecraft. (Ask a Mod/Broadcaster about the version)'];
const none = ['There is currently no modpack being played, right now.'];


module.exports.listpacks = listpacks;

module.exports.po3normal = po3normal;
module.exports.po3titan = po3titan;
module.exports.po3kappa = po3kappa;
module.exports.sf4 = sf4;
module.exports.ragnamodv = ragnamodv;
module.exports.towncraft = towncraft;
module.exports.amnesia = amnesia;
module.exports.rusticwaters = rusticwaters;
module.exports.astroblock = astroblock;
module.exports.volcanoblock = volcanoblock;
module.exports.stoneblock1 = stoneblock1;
module.exports.stoneblock2 = stoneblock2;
module.exports.skyodyssey = skyodyssey;
module.exports.chaoticprogression = chaoticprogression;
module.exports.antichem = antichem;
module.exports.madpack4 = madpack4;
module.exports.rad = rad;
module.exports.rlcraft = rlcraft;
module.exports.mceternal = mceternal
module.exports.enigmatica4 = enigmatica4
module.exports.enigmatica6 = enigmatica6
module.exports.blissfulbuilding = blissfulbuilding
module.exports.infinevo = infinevo
module.exports.infinevo_expert = infinevo_expert
module.exports.skyworkshop = skyworkshop
module.exports.questingmayhem = questingmayhem
module.exports.dimensionzero = dimensionzero
module.exports.ftbacademy = ftbacademy
module.exports.enigmatica2 = enigmatica2
module.exports.enigmatica2ex = enigmatica2ex
module.exports.enigmatica2skyex = enigmatica2skyex
module.exports.atm3ex = atm3ex
module.exports.compactclaustrophobia = compactclaustrophobia
module.exports.ftbinteractions = ftbinteractions
module.exports.trillionaire = trillionaire

module.exports.vanilla = vanilla;
module.exports.none = none;