function newPack({ name = '[Un-named]', launcher = '[Unknown]', link = '[Link Unavailable]', dev = '[Unknown]' }) {

    const data = {
        public: `The current pack is ${name}. You can download it from ${launcher}. -> ${link}`,
        open_beta: `The current pack is ${name}. This is currently an Open Beta. You can download it from ${launcher}. -> ${link}`,
        closed_beta: `The current pack is ${name}. This is currently a Closed Beta. This cannot be downloaded yet.`,
        wip: `The current pack is ${name}. This pack is created by ${dev}. This pack is still in development and cannot be downloaded.`
    };

    return data;
}

export const packlist = {
    acalltoadventure: newPack({ name: 'A Call to Adventure', dev: 'EnderGrimm' }).wip,
    amnesia: newPack({ name: 'Amnesia', launcher: 'CurseForge', link: 'https://www.curseforge.com/minecraft/modpacks/Amnesia' }).public,
    atm3ex: newPack({ name: 'All the Mods 3: Expert Mode', launcher: 'CurseForge', link: 'https://www.curseforge.com/minecraft/modpacks/all-the-mods-3-expert' }).public,
    atm6: newPack({ name: 'All the Mods 6', launcher: 'CurseForge', link: 'https://www.curseforge.com/minecraft/modpacks/all-the-mods-6' }).public,
    atm6sky: newPack({ name: 'All the Mods 6: To The Sky', launcher: 'CurseForge', link: 'https://www.curseforge.com/minecraft/modpacks/all-the-mods-6-to-the-sky-atm6s' }).public,
    antichem: newPack({ name: 'Anti-Matter Chemistry', launcher: 'CurseForge', link: 'https://www.curseforge.com/minecraft/modpacks/antimatter-chemistry' }).public,
    astroblock: newPack({ name: 'AstroBlock', launcher: 'CurseForge', link: 'https://www.curseforge.com/minecraft/modpacks/astroblock' }).public,
    blissfulbuilding: newPack({ name: 'Blissful Building', launcher: 'CurseForge', link: 'https://www.curseforge.com/minecraft/modpacks/blissful-building' }).public,
    chaoticprogression: newPack({ name: 'Chaotic Progression', launcher: 'CurseForge', link: 'https://www.curseforge.com/minecraft/modpacks/chaotic-progression' }).public,
    chromatechnology: newPack({ name: 'Chroma Technology', launcher: 'CurseForge', link: 'https://www.curseforge.com/minecraft/modpacks/chroma-technology' }).public,
    compactclaustrophobia: newPack({ name: 'Compact Claustrophobia', launcher: 'CurseForge', link: 'https://www.curseforge.com/minecraft/modpacks/compact-claustrophobia' }).public,
    damageinc: newPack({ name: 'Damage Inc', launcher: 'CurseForge', link: 'https://www.curseforge.com/minecraft/modpacks/damage-inc-expert' }).public,
    ddss: newPack({ name: 'Dungeons, Dragons and Space Shuttles', launcher: 'CurseForge', link: 'https://www.curseforge.com/minecraft/modpacks/dungeons-dragons-and-space-shuttles' }).public,
    dimensionzero: newPack({ name: 'Dimension Zero', launcher: 'CurseForge', link: 'https://www.curseforge.com/minecraft/modpacks/dimension-zero' }).public,
    disunitysky: newPack({ name: 'Disunity Skyblock', launcher: 'CurseForge', link: 'https://www.curseforge.com/minecraft/modpacks/disunity-skyblock' }).public,
    dw20: newPack({ name: 'DireWolf20', launcher: 'FTB App', link: 'https://feed-the-beast.com/modpack/ftb_presents_direwolf20_1_16' }).public,
    engineerslife: newPack({ name: 'Engineer\'s Life', launcher: 'CurseForge', link: 'https://www.curseforge.com/minecraft/modpacks/engineers-life' }).public,
    engineerslife2: newPack({ name: 'Engineer\'s Life 2', launcher: 'CurseForge', link: 'https://www.curseforge.com/minecraft/modpacks/engineers-life-2' }).public,
    enigmatica2: newPack({ name: 'Enigmatica 2', launcher: 'CurseForge', link: 'https://www.curseforge.com/minecraft/modpacks/enigmatica2' }).public,
    enigmatica2ex: newPack({ name: 'Enigmatica 2: Expert', launcher: 'CurseForge', link: 'https://www.curseforge.com/minecraft/modpacks/enigmatica2expert' }).public,
    enigmatica2skyex: newPack({ name: 'Enigmatica 2 Skyblock: Expert', launcher: 'CurseForge', link: 'https://www.curseforge.com/minecraft/modpacks/enigmatica2expertskyblock' }).public,
    enigmatica4: newPack({ name: 'Enigmatica 4', launcher: 'CurseForge', link: 'https://www.curseforge.com/minecraft/modpacks/enigmatica4' }).public,
    enigmatica6: newPack({ name: 'Enigmatica 6', launcher: 'CurseForge', link: 'https://www.curseforge.com/minecraft/modpacks/enigmatica6' }).public,
    equivalentskies: newPack({ name: 'Equivalent Skies', launcher: 'CurseForge', link: 'https://www.curseforge.com/minecraft/modpacks/equivalent-skies' }).public,
    error404: newPack({ name: 'Error404', dev: 'TheCazadorSniper' }).wip,
    ftbacademy: newPack({ name: 'FTB Academy', launcher: 'CurseForge', link: 'https://www.curseforge.com/minecraft/modpacks/ftb-academy' }).public,
    ftbinteractions: newPack({ name: 'FTB Interactions', launcher: 'FTB App', link: 'https://www.feed-the-beast.com/modpack/ftb_interactions' }).public,
    ftbskyodyssey: newPack({ name: 'FTB Sky Odyssey', launcher: 'CurseForge', link: 'https://www.feed-the-beast.com/projects/ftb-sky-odyssey' }).public,
    glacialawakening: newPack({ name: 'Glacial Awakening', launcher: 'CurseForge', link: 'https://www.curseforge.com/minecraft/modpacks/glacial-awakening' }).public,
    infinevo: newPack({ name: 'FTB Infinity Evolved', launcher: 'CurseForge', link: 'https://www.curseforge.com/minecraft/modpacks/ftb-infinity-evolved' }).public,
    infinevo_expert: newPack({ name: 'FTB Infinity Evolved Expert', launcher: 'CurseForge', link: 'https://www.curseforge.com/minecraft/modpacks/ftb-infinity-evolved' }).public,
    immersive_revolution: newPack({ name: 'Immersive Revolution', launcher: 'CurseForge', link: 'https://www.curseforge.com/minecraft/modpacks/immersive-revolution' }).public,
    levitated: newPack({ name: 'Levitated', launcher: 'CurseForge', link: 'https://www.curseforge.com/minecraft/modpacks/levitated' }).public,
    madpack4: newPack({ name: 'Madpack 4', launcher: 'CurseForge', link: 'https://www.curseforge.com/minecraft/modpacks/madpack-4/' }).public,
    mceternal: newPack({ name: 'MCEternal', launcher: 'CurseForge', link: 'https://www.curseforge.com/minecraft/modpacks/minecraft-eternal' }).public,
    allinone: newPack({ name: 'All in One [Modded One Block]', launcher: 'CurseForge', link: 'https://www.curseforge.com/minecraft/modpacks/all-in-one-modded-one-block' }).public,
    po3normal: newPack({ name: 'Project Ozone 3 Normal', launcher: 'CurseForge', link: 'https://www.curseforge.com/minecraft/modpacks/project-ozone-3-a-new-way-forward' }).public,
    po3titan: newPack({ name: 'Project Ozone 3 Titan', launcher: 'CurseForge', link: 'https://www.curseforge.com/minecraft/modpacks/project-ozone-3-a-new-way-forward' }).public,
    po3kappa: newPack({ name: 'Project Ozone 3 Kappa', launcher: 'CurseForge', link: 'https://www.curseforge.com/minecraft/modpacks/project-ozone-3-a-new-way-forward' }).public,
    questingmayhem: newPack({ name: 'Questing Mayhem', launcher: 'CurseForge', link: 'https://www.curseforge.com/minecraft/modpacks/questing-mayhem' }).public,
    rad: newPack({ name: 'Roguelike Adventures and Dungeons', launcher: 'CurseForge', link: 'https://www.curseforge.com/minecraft/modpacks/roguelike-adventures-and-dungeons' }).public,
    ragnamodv: newPack({ name: 'Ragnamod V', launcher: 'CurseForge', link: 'https://minecraft.curseforge.com/modpacks/ragnamod-v' }).public,
    rlcraft: newPack({ name: 'RLCraft', launcher: 'CurseForge', link: 'https://www.curseforge.com/minecraft/modpacks/rlcraft' }).public,
    rusticwaters: newPack({ name: 'SeaBlock: Rustic Waters', launcher: 'CurseForge', link: 'https://www.curseforge.com/minecraft/modpacks/seablock-rustic-waters' }).public,
    sf4: newPack({ name: 'Sky Factory 4', launcher: 'CurseForge', link: 'https://minecraft.curseforge.com/projects/skyfactory-4' }).public,
    skybees: newPack({ name: 'Sky Bees', launcher: 'CurseForge', link: 'https://www.curseforge.com/minecraft/modpacks/sky-bees' }).public,
    skyofdiamonds: newPack({ name: 'Awakening: Sky of Diamonds', launcher: 'CurseForge', link: 'https://www.curseforge.com/minecraft/modpacks/awakening-sky-of-diamonds' }).public,
    skyopolis: newPack({ name: 'Skyopolis', launcher: 'CurseForge', link: 'https://www.curseforge.com/minecraft/modpacks/skyopolis' }).public,
    skyopolis2: newPack({ name: 'Skyopolis 2', launcher: 'CurseForge', link: 'https://www.curseforge.com/minecraft/modpacks/skyopolis-2' }).public,
    skyopolis3: newPack({ name: 'Skyopolis 3', launcher: 'CurseForge', link: 'https://www.curseforge.com/minecraft/modpacks/skyopolis-3' }).public,
    skyopolis4: newPack({ name: 'Skyopolis 4', launcher: 'CurseForge', link: 'https://www.curseforge.com/minecraft/modpacks/skyopolis-4' }).public,
    skyworkshop: newPack({ name: 'SkyWorkshop', launcher: 'CurseForge', link: 'https://www.curseforge.com/minecraft/modpacks/skyworkshop' }).public,
    stacia_expert: newPack({ name: 'Stacia Expert', launcher: 'CurseForge', link: 'https://www.curseforge.com/minecraft/modpacks/stacia-expert' }).public,
    starfactory: newPack({ name: 'Star Factory', launcher: 'CurseForge', link: 'https://www.curseforge.com/minecraft/modpacks/star-factory' }).public,
    stoneblock1: newPack({ name: 'StoneBlock 1', launcher: 'CurseForge', link: 'https://www.curseforge.com/minecraft/modpacks/stoneblock' }).public,
    stoneblock2: newPack({ name: 'StoneBlock 2', launcher: 'CurseForge', link: 'https://www.curseforge.com/minecraft/modpacks/ftb-presents-stoneblock-2/' }).public,
    towncraft: newPack({ name: 'TownCraft', launcher: 'CurseForge', link: 'https://minecraft.curseforge.com/projects/towncraft' }).public,
    trillionaire: newPack({ name: 'Minecraft Trillionaire', launcher: 'CurseForge', link: 'https://www.curseforge.com/minecraft/modpacks/minecraft-trillionaire' }).public,
    volcanoblock: newPack({ name: 'Volcano Block', launcher: 'CurseForge', link: 'https://www.curseforge.com/minecraft/modpacks/volcano-block' }).public,
    vaulthunters: newPack({ name: 'Vault Hunters', launcher: 'CurseForge', link: 'https://www.curseforge.com/minecraft/modpacks/vault-hunters-official-modpack' }).public,

    // Non-Modded
    vanilla: 'This is Vanilla Minecraft. (Ask a Mod/Broadcaster about the version)',
    vanillaplus: 'This is Vanilla Minecraft with a few minor mods added for convenience. (Ask a Mod/Broadcaster about the version)',
    none: 'There is currently no modpack being played, right now.'
};